export const DIMENSIONS = {
  paddingNormal: 16,
  paddingLarge: 36,
  marginNormal: 16,
  marginMedium: 24,
  paddingMedium: 24,
  marginSmall: 8,
  paddingSmall: 8,
  marginLarge: 36,
  actionableHeight: 48,
  radius: 6,
  radiusLarge: 12,
  radiusXLarge: 36,
  borderWidth: 1,
};
